/*-- DROP ALL TABLE
BEGIN
    -- Drop all tables
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;

    -- Drop all sequences
    FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

*/
/*-- DROP ALL TABLE
BEGIN
   FOR t IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
*/

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER XAYDUNG IDENTIFIED BY password;
GRANT CONNECT, RESOURCE, DBA TO XAYDUNG;

-- Sử dụng Schema

ALTER SESSION SET CURRENT_SCHEMA = XAYDUNG;

-- Tạo bảng LOAIXD
CREATE TABLE LOAIXD (
    MaLXD VARCHAR2(10) PRIMARY KEY,
    TenLXD VARCHAR2(100) NOT NULL
);

-- Tạo bảng XANGDAU
CREATE TABLE XANGDAU (
    MaXD VARCHAR2(10) PRIMARY KEY,
    TenXD VARCHAR2(100) NOT NULL,
    GiaCoSo FLOAT NOT NULL,
    MaLXD VARCHAR2(10),
    FOREIGN KEY (MaLXD) REFERENCES LOAIXD(MaLXD)
);

-- Tạo bảng CUAHANG
CREATE TABLE CUAHANG (
    MaCH VARCHAR2(10) PRIMARY KEY,
    TenCH VARCHAR2(100) NOT NULL,
    ChuCH VARCHAR2(100) NOT NULL,
    DiaChi VARCHAR2(200) NOT NULL,
    SDT VARCHAR2(15) NOT NULL
);

-- Tạo bảng NHAP
CREATE TABLE NHAP (
    MaCH VARCHAR2(10),
    MaXD VARCHAR2(10),
    NgayNhap VARCHAR2(10) NOT NULL, -- Changed to VARCHAR2
    SoLuong INT NOT NULL,
    GiaNhap FLOAT NOT NULL,
    PRIMARY KEY (MaCH, MaXD, NgayNhap),
    FOREIGN KEY (MaCH) REFERENCES CUAHANG(MaCH),
    FOREIGN KEY (MaXD) REFERENCES XANGDAU(MaXD)
);

-- Tạo sequence cho MaXD
CREATE SEQUENCE seq_MaXD
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tạo sequence cho MaCH
CREATE SEQUENCE seq_MaCH
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Tạo trigger để tự động điền MaXD
CREATE OR REPLACE TRIGGER trg_MaXD
BEFORE INSERT ON XANGDAU
FOR EACH ROW
BEGIN
  SELECT 'XD' || TO_CHAR(seq_MaXD.NEXTVAL, 'FM0000') INTO :NEW.MaXD FROM DUAL;
END;
/

-- Tạo trigger để tự động điền MaCH
CREATE OR REPLACE TRIGGER trg_MaCH
BEFORE INSERT ON CUAHANG
FOR EACH ROW
BEGIN
  SELECT 'CH' || TO_CHAR(seq_MaCH.NEXTVAL, 'FM0000') INTO :NEW.MaCH FROM DUAL;
END;
/

-- Thêm dữ liệu mẫu vào bảng LOAIXD
INSERT INTO LOAIXD (MaLXD, TenLXD) VALUES ('LXD01', 'Dầu Diesel');
INSERT INTO LOAIXD (MaLXD, TenLXD) VALUES ('LXD02', 'Xăng A92');
INSERT INTO LOAIXD (MaLXD, TenLXD) VALUES ('LXD03', 'Xăng A95');

-- Thêm dữ liệu mẫu vào bảng XANGDAU
INSERT INTO XANGDAU (TenXD, GiaCoSo, MaLXD) VALUES ('Dầu Diesel', 15000.5, 'LXD01');
INSERT INTO XANGDAU (TenXD, GiaCoSo, MaLXD) VALUES ('Xăng A92', 17000.0, 'LXD02');
INSERT INTO XANGDAU (TenXD, GiaCoSo, MaLXD) VALUES ('Xăng A95', 18000.0, 'LXD03');

-- Thêm dữ liệu mẫu vào bảng CUAHANG
INSERT INTO CUAHANG (TenCH, ChuCH, DiaChi, SDT) VALUES ('Cửa hàng 1', 'Nguyễn Văn A', '123 Đường A', '0912345678');
INSERT INTO CUAHANG (TenCH, ChuCH, DiaChi, SDT) VALUES ('Cửa hàng 2', 'Trần Văn B', '456 Đường B', '0987654321');

-- Thêm dữ liệu mẫu vào bảng NHAP (sử dụng 'dd/MM/yyyy' cho NgayNhap)
INSERT INTO NHAP (MaCH, MaXD, NgayNhap, SoLuong, GiaNhap) VALUES ('CH0001', 'XD0001', '01/06/2023', 100, 15500.0);
INSERT INTO NHAP (MaCH, MaXD, NgayNhap, SoLuong, GiaNhap) VALUES ('CH0002', 'XD0002', '15/06/2023', 200, 17200.0);
