/*-- DROP ALL TABLE
BEGIN
   FOR t IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
*/

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER PHONGKHAM IDENTIFIED BY password;
GRANT CONNECT, RESOURCE, DBA TO PHONGKHAM;

-- Sử dụng Schema

ALTER SESSION SET CURRENT_SCHEMA = PHONGKHAM;